spring:
  application:
    name: spring-kotlin
  profiles:
    active: local
  config:
    import:
      - logging.yml
      - db-core.yml
      - redis.yml
  cache:
    type: redis

---
spring:
  config:
    activate:
      on-profile: local

---
