spring:
  application:
    name: spring-kotlin
  profiles:
    active: local
  config:
    import:
      - logging.yml
      - db-core.yml
      - redis.yml

---
spring:
  config:
    activate:
      on-profile: local

---
