spring:
  cloud:
    compatibility-verifier:
      enabled: false
#  sleuth:
#    trace-id128: true
#    sampler:
#      probability: 1.0

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml